### ISSUE TITLE
Hole obstacle is not triggering on hit

### ISSUE THREAD

**Issue by ZaneLittle** [ZaneLittle/SundayStroll#48]
Obstacle is too low for the player to ever hit it
![2019-02-14_19-57-51](https://user-images.githubusercontent.com/32856644/52828063-422cbf80-3095-11e9-9ccc-d1951cb70047.gif)

**Comment by stefanuros** [comment]
Its probably too low. I may have moved the ground up a bit when creating the parallax.

**Comment by ZaneLittle** [comment]
Yeah, I just need to move up the the spawn point in the obstacle spawner script
