### ISSUE TITLE
'GameObject' prefab is not descriptive

### ISSUE THREAD

**Issue by ZaneLittle** [ZaneLittle/SundayStroll#57]
Is the 'GameObject' prefab being used? If it is, it should have a more descriptive name. If not, it should be removed.

![image](https://user-images.githubusercontent.com/32856644/52978295-a3f36f00-339e-11e9-80ca-bc070f0881ef.png)

**Comment by ZaneLittle** [comment]
I'm going to assign you @stefanuros because I think you added it as it has something to do with the particle system.

**Comment by stefanuros** [comment]
I think that was before I renamed it. I'll fix it. I think I just need to replace it with the current particle burst cause I think that's what it is
