### ISSUE TITLE
Generate Obstacles

### ISSUE THREAD

**Issue by stefanuros** [ZaneLittle/SundayStroll#9]
Create an object that will generate obstacles on the right hand side of the screen and move towards the player

**Comment by ZaneLittle** [comment]
I will implement 3 `spawner' objects that each create an obstacle at its location. One will be at ground level, another at head level, and a third in the ground.

**Comment by ZaneLittle** [comment]
This creates the problem where there is unbeatable parts. Instead, there will be one spawner that creates the obstacles at 3 different heights.
